name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - name: Run Tests
        run: "zig build test"
      - name: Build VST
        run: "zig build -Drelease-fast"
      - name: 'Tar .vst directory'
        run: tar -cvf zig-analyzer.vst.tar zig-cache/vst/zig-analyzer.vst
      - uses: actions/upload-artifact@v2
        with:
          name: zig-analyzer-macos-${{ github.sha }}.vst
          path: zig-analyzer.vst.tar

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - name: Run Tests
        run: "zig build test"
      - name: Build VST
        run: "zig build -Drelease-fast"
      - uses: actions/upload-artifact@v2
        with:
          name: zig-analyzer-windows-${{ github.sha }}.dll
          path: zig-cache/lib/zig-analyzer.dll
